name: Build and Release Flatpak

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Flatpak
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: Gameyfin-Desktop-${{ github.ref_name }}.flatpak
        manifest-path: org.gameyfin.Gameyfin-Desktop.yaml
        cache-key: flatpak-builder-${{ github.sha }}

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: ${{ endsWith(github.ref_name, '-dev') }}
        files: Gameyfin-Desktop-${{ github.ref_name }}.flatpak
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}